### ISSUE TITLE
TC1激活功能

### ISSUE THREAD

**Issue by ghostist** [HuaZao/TC1-NG#2]
https://github.com/a2633063/SmartControl_Android_MQTT
原版SmartControl_Android_MQTT 对最新的TC1固件增加了激活码功能
（DC1一直需要）
如打算后期让TC1-NG支持DC1，建议加入激活码输入功能
否则可以用原版配网激活后，使用TC1-NG控制

**Comment by HuaZao** [comment]
已经添加上了~
