### ISSUE TITLE
请教一个问题，输入密码点击配置后，会发生loading转圈一下然后消失。然后重复在这样的界面。

### ISSUE THREAD

**Issue by smart-z** [HuaZao/TC1-NG#3]
并没有发生“观察TC1的指示灯,快闪然后常亮则配网成功,此时APP无任何反应 ”这一步。

**Comment by HuaZao** [comment]
如果是自签的话,需要加上WIFI权限(Access WIFI )哦~不然软件是获取不到当前WIFI信息哦
Notice:
1.个人证书无法添加Access WIFI的权限,建议使用安卓配网
2.如果实在没有安卓设备,可以在商店搜索EasyLinkLite进行配网操作

**Comment by smart-z** [comment]
> 如果是自签的话,需要加上WIFI权限(Access WIFI )哦~不然软件是获取不到当前WIFI信息哦
> Notice:
> 1.个人证书无法添加Access WIFI的权限,建议使用安卓配网
> 2.如果实在没有安卓设备,可以在商店搜索EasyLinkLite进行配网操作

感谢感谢，总算是看到希望了，我先折腾折腾，先谢谢了

**Comment by HuaZao** [comment]
> > 如果是自签的话，需要加上WIFI权限（访问WIFI）哦〜不然软件是获取不到当前WIFI信息哦
> > 注意：
> > 1。个人证书无法添加访问WIFI的权限，建议使用安卓配网
> > 2.如果实在没有安卓设备，可以在商店搜索EasyLinkLite进行配网操作
> 
> 感谢感谢，总算是看到希望了，我先折腾折腾，先谢谢了

APP配网页面有个调试功能,点击蓝色的WIFI图标可以手动输入WIFI名字,不过我没有进行过测试,有可能配对不了

**Comment by smart-z** [comment]
> > > 如果是自签的话，需要加上WIFI权限（访问WIFI）哦〜不然软件是获取不到当前WIFI信息哦
> > > 注意：
> > > 1。个人证书无法添加访问WIFI的权限，建议使用安卓配网
> > > 2.如果实在没有安卓设备，可以在商店搜索EasyLinkLite进行配网操作
> > 
> > 
> > 感谢感谢，总算是看到希望了，我先折腾折腾，先谢谢了
> 
> APP配网页面有个调试功能,点击蓝色的WIFI图标可以手动输入WIFI名字,不过我没有进行过测试,有可能配对不了

就是点蓝色的WIFI图标这个操作搞定了。
但是我发现激活码是不是没有地方来输入呢？点激活码相关区域，木有反应。

**Comment by HuaZao** [comment]
> > > > 如果是自签的话，需要加上WIFI权限（访问WIFI）哦〜不然软件是获取不到当前WIFI信息哦
> > > > 注意：
> > > > 1。个人证书无法添加访问WIFI的权限，建议使用安卓配网
> > > > 2.如果实在没有安卓设备，可以在商店搜索EasyLinkLite进行配网操作
> > > 
> > > 
> > > 感谢感谢，总算是看到希望了，我先折腾折腾，先谢谢了
> > 
> > 
> > APP配网页面有个调试功能,点击蓝色的WIFI图标可以手动输入WIFI名字,不过我没有进行过测试,有可能配对不了
> 
> 就是点蓝色的WIFI图标这个操作搞定了。
> 但是我发现激活码是不是没有地方来输入呢？点激活码相关区域，木有反应。

请确认你的排插固件版本号大于10.3,如果尚未激活,进入操作界面自动提示需要激活

**Comment by smart-z** [comment]
> > > > > 如果是自签的话，需要加上WIFI权限（访问WIFI）哦〜不然软件是获取不到当前WIFI信息哦
> > > > > 注意：
> > > > > 1。个人证书无法添加访问WIFI的权限，建议使用安卓配网
> > > > > 2.如果实在没有安卓设备，可以在商店搜索EasyLinkLite进行配网操作
> > > > 
> > > > 
> > > > 感谢感谢，总算是看到希望了，我先折腾折腾，先谢谢了
> > > 
> > > 
> > > APP配网页面有个调试功能,点击蓝色的WIFI图标可以手动输入WIFI名字,不过我没有进行过测试,有可能配对不了
> > 
> > 
> > 就是点蓝色的WIFI图标这个操作搞定了。
> > 但是我发现激活码是不是没有地方来输入呢？点激活码相关区域，木有反应。
> 
> 请确认你的排插固件版本号大于10.3,如果尚未激活,进入操作界面自动提示需要激活

再次感谢，真是一波三折呀。我是从github直接下载的固件。安装了您的iOS端。这个固件上点击版本号看不到信息，只有两个ota相关。哎呀呀一波三折。我这改从哪里找个ota呀？固件木有，ota木有。呀呀呀～～～再次感谢感谢

**Comment by smart-z** [comment]
> > > > > 如果是自签的话，需要加上WIFI权限（访问WIFI）哦〜不然软件是获取不到当前WIFI信息哦
> > > > > 注意：
> > > > > 1。个人证书无法添加访问WIFI的权限，建议使用安卓配网
> > > > > 2.如果实在没有安卓设备，可以在商店搜索EasyLinkLite进行配网操作
> > > > 
> > > > 
> > > > 感谢感谢，总算是看到希望了，我先折腾折腾，先谢谢了
> > > 
> > > 
> > > APP配网页面有个调试功能,点击蓝色的WIFI图标可以手动输入WIFI名字,不过我没有进行过测试,有可能配对不了
> > 
> > 
> > 就是点蓝色的WIFI图标这个操作搞定了。
> > 但是我发现激活码是不是没有地方来输入呢？点激活码相关区域，木有反应。
> 
> 请确认你的排插固件版本号大于10.3,如果尚未激活,进入操作界面自动提示需要激活


亲，10.3有木有办法激活呢？似乎官方ota恢复了，终于更新到10.3了，我现在的版本就是10.3。

我在绑定成功的那一刻app其实闪退了，再重新进来显示已经连上了，点进来操作此时我的10.3是没有激活提示的。您说的激活一定要大于10.3的版本吗？奈何目前ota最新也就是10.3。

如果10.3可以激活的话，那您看是不是可以再加个激活的入口，就加到设备状态那里也好呀？感激感激。

**Comment by HuaZao** [comment]
如果是用UDP协议,可能不太稳定,没有接受到插座的激活数据,建议自己搭建MQTT服务器!实在不能搭建MQTT服务器,重新多进几次,或者用安卓设备去激活!
